const express = require("express");

const router = express.Router();

router.get("/GetSuggestionAddress", (req, res) => {
  res.setHeader("Content-Type", "application/json");
  res.status(200);
  res.json({
    Data: {
      DaData: [
        {
          SearchAccuracy: {
            Address: "г Санкт-Петербург",
            ShortAddress: "г Санкт-Петербург",
            FullAddress: "190000, г Санкт-Петербург",
            RegionWithType: "г Санкт-Петербург",
            RegionType: "г",
            Region: "Санкт-Петербург",
            RegionName: "Санкт-Петербург",
            RegionId: "c2deb16a-0330-4f05-821f-1d09c93331e6",
            DistrictWithType: null,
            DistrictType: null,
            District: null,
            DistrictName: null,
            DistrictId: null,
            CityWithType: "г Санкт-Петербург",
            CityType: "г",
            City: "Санкт-Петербург",
            CityName: "Санкт-Петербург",
            CityId: "c2deb16a-0330-4f05-821f-1d09c93331e6",
            LocalityWithType: null,
            LocalityWith: null,
            LocalityType: null,
            Locality: null,
            LocalityName: null,
            LocalityId: null,
            StreetWithType: 'StreetWithType',
            StreetType: null,
            Street: null,
            StreetName: null,
            StreetId: null,
            HouseType: null,
            House: 'House',
            HouseName: null,
            HouseId: null,
            BlockType: null,
            Block: null,
            BuildingType: null,
            BuildingName: null,
            PostIndex: "190000",
            RegionCode: "RU-SPE",
            Area: null,
          },
          Key: "",
          Value: "",
        },
        {
          SearchAccuracy: {
            Address: "г Санкт-Петербург",
            ShortAddress: "г Санкт-Петербург",
            FullAddress: "190000, г Санкт-Петербург",
            RegionWithType: "г Санкт-Петербург",
            RegionType: "г",
            Region: "Санкт-Петербург",
            RegionName: "Санкт-Петербург",
            RegionId: "c2deb16a-0330-4f05-821f-1d09c93331e6",
            DistrictWithType: null,
            DistrictType: null,
            District: null,
            DistrictName: null,
            DistrictId: null,
            CityWithType: "г Санкт-Петербург",
            CityType: "г",
            City: "Санкт-Петербург",
            CityName: "Санкт-Петербург",
            CityId: "c2deb16a-0330-4f05-821f-1d09c93331e6",
            LocalityWithType: null,
            LocalityWith: null,
            LocalityType: null,
            Locality: null,
            LocalityName: null,
            LocalityId: null,
            StreetWithType: null,
            StreetType: null,
            Street: null,
            StreetName: null,
            StreetId: null,
            HouseType: null,
            House: null,
            HouseName: null,
            HouseId: null,
            BlockType: null,
            Block: null,
            BuildingType: null,
            BuildingName: null,
            PostIndex: "190000",
            RegionCode: "RU-SPE",
            Area: null,
          },
          Key: "",
          Value: "",
        },
        {
          SearchAccuracy: {
            Address: "г Санкт-Петербург",
            ShortAddress: "г Санкт-Петербург",
            FullAddress: "190000, г Санкт-Петербург",
            RegionWithType: "г Санкт-Петербург",
            RegionType: "г",
            Region: "Санкт-Петербург",
            RegionName: "Санкт-Петербург",
            RegionId: "c2deb16a-0330-4f05-821f-1d09c93331e6",
            DistrictWithType: null,
            DistrictType: null,
            District: null,
            DistrictName: null,
            DistrictId: null,
            CityWithType: "г Санкт-Петербург",
            CityType: "г",
            City: "Санкт-Петербург",
            CityName: "Санкт-Петербург",
            CityId: "c2deb16a-0330-4f05-821f-1d09c93331e6",
            LocalityWithType: null,
            LocalityWith: null,
            LocalityType: null,
            Locality: null,
            LocalityName: null,
            LocalityId: null,
            StreetWithType: 'StreetWithType',
            StreetType: null,
            Street: null,
            StreetName: null,
            StreetId: null,
            HouseType: null,
            House: 'House',
            HouseName: null,
            HouseId: null,
            BlockType: null,
            Block: null,
            BuildingType: null,
            BuildingName: null,
            PostIndex: "190000",
            RegionCode: "RU-SPE",
            Area: null,
          },
          Key: "",
          Value: "",
        },
      ],
    },
  });
});

module.exports = router;
